# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || 首页
  galleries: /galleries/ || 相册
  archives: /archives/ || 归档
  tags: /tags/ || 标签
  categories: /categories/ || 分类
  # about: /about/ || 关于

# Color
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'
  link-gradient: 'linear-gradient(-60deg, #ff5858 0%, #f09819 100%)'

# Favicon
favicon:
  small: /images/icons/favicon-16x16.ico
  medium: /images/icons/favicon-32x32.ico
  # apple_touch_icon: /images/icons/apple-touch-icon.png
  # safari_pinned_tab: /images/icons/stun-logo.svg
  # msapplication: /images/icons/favicon-144x144.png

# Font
font:
  size: 16px
  family: sans-serif, system-ui

# Background Image
background_image:

# Loading
loading:
  gif: /images/theme/loading.gif
  lottie:

# Preview
preview:
  enable: true
  type: wave  # wave | cloud
  background:
    type: image # image video
    default_image:
      light: # /images/theme/welcome-background.jpg
      dark: # /images/theme/welcome-background.jpg
    video:
    api: https://api.unsplash.com/photos/random?client_id=WTOQU8thNHmm9MzBYV6L5ERpE_l4yg76nYuMZYiYD5s&orientation=landscape&query=nature,scenery,arts
    return_type: json
    data_contents: ['urls', 'regular']
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: 菡萏香销翠叶残，西风愁起绿波间。
    color: '#ffffff'
    typing: true
    api: https://v2.jinrishici.com/one.json
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true
  back_home: true

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  qq: # tencent://message/?Menu=yes&uin=894519210 || iconQQ || '#12B7F5'
  wechat: https://iaosee.com/images/resource/iaosee-wechat.jpg || iconwechat-fill || '#09BB07'
  instagram: # https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/iaosee || icongithub-fill || '#9f7be1'
  email: mailto:iaosee@outlook.com || iconmail
  # weibo: https://www.weibo.com/u/5118348162 || iconweibo || '#DA2E76'

# Override Scrollbar
scrollbar:
  model: simple # default simple normal none

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# Search
search:
  enable: false

# QR Code
qrcode:
  enable: false
  type: url # url image
  image: https://pic.izhaoo.com/weapp-code.jpg

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Excerpt
excerpt:
  enable: true

# Post Image
post_image:
  random: local # local galleries
  default: /images/theme/post-image.jpg

# Page Size
post_page_size:
  width: 1200px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate
donate:
  enable: false
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 相册
  subtitle: Photography
  type: waterfall # waterfall | grid
  columns: 3


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: true
  type: giscus # gitalk | valine | changyan | giscus
  button: false

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId: QRsYxiOY3VGeVhkqx7yJiz0U-gzGzoHsz
  appKey: 1ygwFPYG8IbvlgnrnNXrNeNe
  placeholder: 踩个脚印
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# https://giscus.app/zh-CN
giscus:
  repo: iaosee/iaosee.github.io
  repoId: MDEwOlJlcG9zaXRvcnk4ODczNjY2Ng==
  mapping: pathname
  category: Announcements
  categoryId: DIC_kwDOBUoDms4CQP9t
  inputPosition: top
  reactionsEnabled: 1
  emitMetadata: 0
  lang: zh-CN

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: fb486b7c  # app_id

# Tencent Chao
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: true
  appId: QRsYxiOY3VGeVhkqx7yJiz0U-gzGzoHsz
  appKey: 1ygwFPYG8IbvlgnrnNXrNeNe
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading:
    gif: /images/theme/loading.gif
    lottie:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  line_number: true
  auto_detect: true
  style: # https://highlightjs.org/demo/
    light: Github
    dark: Github Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: fa215b20eccf04179a4d316087693164 # id
  google: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
# - https://unpkg.zhihu.com/
# - https://github.com/54ayao/JSDMirror
# - https://iui.su/3635/
vendors:
  jquery_js: https://code.jquery.com/jquery-3.6.0.min.js
  fancybox_js: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  lottie_js: https://cdn.jsdelivr.net/npm/lottie-web@5.12.2/build/player/lottie.min.js
  fancybox_css: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/highlight.js/11.4.0/styles/
  iconfont_css: https://at.alicdn.com/t/font_1445822_p6ry5n7lrr.css
  # mathjax_js: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

# Custom
custom:
  head: # <script src="https://cdn.jsdelivr.net/npm/mathjs@14.0.0/lib/browser/math.min.js"></script>
  foot: # <script src="//code.tidio.co/0lsap9qzw3koor7fwowzwupvksb0tosb.js" async></script>
  css:
  js:
